apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 80
    targetPort: "http-server"
    nodePort: 30001
  selector:
    app: guestbook
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 3
  template:
    metadata:
      labels:
       app: guestbook
    spec:
      containers:
      - name: guestbook
        image: moretea/guestbook-go
        ports:
          - name: http-server
            containerPort: 3000

